AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda that generates images using Google Gemini (Python).

# Parameters capture values that may vary across environments or deployments.
Parameters:
  GoogleApiKeyParameterName:
    Type: String
    Description: Secure parameter name in AWS Systems Manager Parameter Store that stores the Gemini API key.
  LambdaFunctionName:
    Type: String
    Default: lambda-gemini-api
    Description: Name to assign to the Lambda function.

# Globals define defaults applied to every AWS::Serverless::Function in this template.
Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512
    Handler: src/app.lambda_handler
    Architectures:
      - arm64
    Environment:
      Variables:
        GOOGLE_API_KEY_PARAM: !Ref GoogleApiKeyParameterName

Resources:
  RestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: AWS_IAM

  GeminiImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Description: Generates images with Gemini based on custom prompts.
      CodeUri: .
      # Inline policies allow the function to read the secure parameter and decrypt it with the managed SSM key.
      Policies:
        - Statement:
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:GetParameterHistory
            Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter${GoogleApiKeyParameterName}
        - Statement:
            Effect: Allow
            Action:
              - kms:Decrypt
            Resource: !Sub arn:aws:kms:${AWS::Region}:${AWS::AccountId}:alias/aws/ssm
      Events:
        ApiRequest:
          Type: Api
          Properties:
            RestApiId: !Ref RestApi
            # Expose a POST endpoint so API Gateway can trigger the Lambda with user prompts.
            Path: /generate-image
            Method: post

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint to invoke the function.
    # Expose the HTTPS URL created by API Gateway so clients can consume the service.
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-image"
