AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda que genera imágenes usando Google Gemini (Python).

Parameters:
  GoogleApiKeyParameterName:
    Type: String
    Description: Nombre del parámetro seguro en AWS Systems Manager Parameter Store que contiene la API key de Gemini.
  LambdaFunctionName:
    Type: String
    Default: lambda-gemini-api
    Description: Nombre que tendrá la función Lambda.

Globals:
  Function:
    Runtime: python3.12
    Timeout: 30
    MemorySize: 512
    Handler: src/app.lambda_handler
    Architectures:
      - arm64
    Environment:
      Variables:
        GOOGLE_API_KEY: !Sub "{{resolve:ssm-secure:${GoogleApiKeyParameterName}:1}}"
    Policies:
      - SSMParameterReadPolicy:
          ParameterName: !Ref GoogleApiKeyParameterName

Resources:
  GeminiImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Description: Genera imágenes con Gemini usando prompts personalizados.
      CodeUri: .
      Events:
        ApiRequest:
          Type: Api
          Properties:
            Path: /generate-image
            Method: post

Outputs:
  ApiEndpoint:
    Description: Endpoint expuesto por API Gateway para invocar la función.
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate-image"
